### PR TITLE
add GXM.plugin.Tracker for geolocation

### PR DESCRIPTION
**Pull request by bartvde**

### CODE REVIEW

**Comment by marcjansen** [comment]
Looks fine to me, please merge.

**Comment by bartvde** [comment]
@marcjansen thanks for your review.
However there have been some changes since I did this pull in the opengeo GXM branch so I'll need to update the pull request.

**Comment by marcjansen** [comment]
@bartvde Ok for me.

**Comment by bartvde** [comment]
Closing this one, will open up a new one for the new code.

**Pull request closed without merging**
